AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RoleName:
    Type: String
    Default: NetworkProvider
    Description: Role name for all accounts
  ProviderLambdaRole:
    Type: String
    Default: "arn:aws:iam::123456789012:role/function_lambda_role"
    Description: "Enter Network Provider Lambda Role."

Resources:
  #####################################################################
  ################## Network Provider Trust Role ######################
  #####################################################################
  NetworkProviderTrust:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Path: /
      Policies:
        - PolicyName: default
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:DeleteSubnet
                  - ec2:ReplaceRouteTableAssociation
                  - ec2:ModifyVpcEndpointServiceConfiguration
                  - ec2:CreateTransitGatewayConnect
                  - ec2:DeleteVpcEndpoints
                  - ec2:AttachInternetGateway
                  - ec2:AcceptTransitGatewayVpcAttachment
                  - ec2:UpdateSecurityGroupRuleDescriptionsIngress
                  - ec2:AssociateRouteTable
                  - ec2:DeleteRouteTable
                  - ec2:DescribeInternetGateways
                  - ec2:DeleteTransitGatewayVpcAttachment
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:CreateRoute
                  - ec2:CreateInternetGateway
                  - ec2:DeleteInternetGateway
                  - ec2:DescribeRouteTables
                  - ec2:UpdateSecurityGroupRuleDescriptionsEgress
                  - ec2:CreateVpcEndpointConnectionNotification
                  - ec2:CreateTags
                  - ec2:CreateRouteTable
                  - ec2:DeleteNetworkInterface
                  - ec2:GetTransitGatewayAttachmentPropagations
                  - ec2:ModifySecurityGroupRules
                  - ec2:DetachInternetGateway
                  - ec2:DescribeVpcEndpointServiceConfigurations
                  - ec2:DisassociateRouteTable
                  - ec2:ModifyVpcEndpointConnectionNotification
                  - ec2:CreateVpcEndpointServiceConfiguration
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeVpcEndpointServicePermissions
                  - ec2:DescribeTransitGatewayAttachments
                  - ec2:CreateTransitGatewayVpcAttachment
                  - ec2:DescribeSecurityGroupRules
                  - ec2:DeleteNatGateway
                  - ec2:DescribeVpcEndpoints
                  - ec2:DeleteVpc
                  - ec2:CreateEgressOnlyInternetGateway
                  - ec2:EnableTransitGatewayRouteTablePropagation
                  - ec2:CreateSubnet
                  - ec2:DescribeSubnets
                  - ec2:ModifyVpcEndpoint
                  - ec2:DisassociateAddress
                  - ec2:ModifyVpcEndpointServicePermissions
                  - ec2:ModifyPrivateDnsNameOptions
                  - ec2:DescribeAddresses
                  - ec2:DeleteTags
                  - ec2:CreateNatGateway
                  - ec2:DescribeRegions
                  - ec2:CreateVpc
                  - ec2:DescribeVpcEndpointServices
                  - ec2:DeleteVpcEndpointServiceConfigurations
                  - ec2:DescribeVpcAttribute
                  - ec2:ModifySubnetAttribute
                  - ec2:DescribeAvailabilityZones
                  - ec2:CreateSecurityGroup
                  - ec2:ModifyVpcAttribute
                  - ec2:DescribeVpcEndpointConnections
                  - ec2:GetTransitGatewayRouteTableAssociations
                  - ec2:ReleaseAddress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:ModifyTransitGatewayVpcAttachment
                  - ec2:DeleteEgressOnlyInternetGateway
                  - ec2:DetachNetworkInterface
                  - ec2:DeleteRoute
                  - ec2:DescribeNatGateways
                  - ec2:DescribeVpcEndpointConnectionNotifications
                  - ec2:AllocateAddress
                  - ec2:DescribeSecurityGroups
                  - ec2:DeleteVpcEndpointConnectionNotifications
                  - ec2:DescribeSecurityGroupReferences
                  - ec2:DescribeVpcs
                  - ec2:CreateVpcEndpoint
                  - ec2:DeleteSecurityGroup
                  - ec2:DescribeTransitGatewayVpcAttachments
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:GetTemplateSummary
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:GetTemplate
                  - cloudformation:DeleteStack
                  - cloudformation:UpdateStack
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                Resource:
                  - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/network-*/*"

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref "ProviderLambdaRole"
            Action: sts:AssumeRole
      Tags:
        - Key: "application"
          Value: "network-api"
